[project]
name = "obljudge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.9"
dependencies = [
    "httpx>=0.28.1",
    "pydantic>=2.12.3",
    "pydantic-ai>=1.7.0",
]
